<?php

 $title = 'My Playlist';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('playlist', array('action'=>'add'));?>">Add new Music</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 
 <?php 
 
 foreach ($playlists as $playlist) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($playlist->title);?></td>
     <td><?php echo $this->escapeHtml($playlist->artist);?></td>
     <td>
         <a href="<?php echo $this->url('playlist',
             array('action'=>'delete', 'id' => $playlist->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 
  <p>
     <a class="btn btn-success" href="<?php echo $this->url('logout');?>">Deconnexion</a>
 </p>