<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sMusic Play%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('You are in our application in witch you can manage your %splaylist%s. You need some music you can find it in our application. So, let yourself be transported by the music'),  '<span class="zf-green">', '</span>', \Zend\Version\Version::VERSION) ?></p>

</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover our application') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Music Play is an application which,is in development. %sDaily%s, new music, album are add in the application in order it is suitable for all tastes !'),'<span class="zf-green">', '</span>') ?></p>
                <p><a class="btn btn-success pull-right" href="login"target="_blank"><?php echo $this->translate('Login') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('More about us') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you want to know more about us, check our work to %shttps://github.com/1s2vanessa/music2.git%s'),'<a href="https://github.com/1s2vanessa/music2" >','</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="https://github.com/1s2vanessa/music2" target="_blank"><?php echo $this->translate('Go to') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
