<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sMusic Play%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('You are in our application in witch you can manage your %splaylist%s. You need some music you can find it in our application. So, let yourself be transported by the music'),  '<span class="zf-green">', '</span>', \Zend\Version\Version::VERSION) ?></p>

</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover our application') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Music Play is an application which,is in development. %sDaily%s, new music, album are add in the application in order it is suitable for all tastes !'),'<span class="zf-green">', '</span>') ?></p>
                <p><a class="btn btn-success pull-right" href="login"target="_blank"><?php echo $this->translate('Login') ?> &raquo;</a></p>
                 
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Us') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('You can follow us on FB and Twitter : .... .Don\'t hesitate to share your ideas contacting us ')) ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while using our application, you may reach us via ....: %s#MPlay%s. We\'d love to hear any questions or feedback you may have regarding the beta releases.'),  '<span class="zf-green">', '</span>') ?></p>
                <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Contact Us') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
